services:
  backend:
    build: .
    container_name: fshop_backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: username
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: fshop_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: node dist/main.js 
  postgres:
    image: postgres:16-alpine
    container_name: fshop_postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fshop_db
    ports:
      - "5432:5432"
    volumes:
      - fshop_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fshop_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - fshop_redis_data:/data

volumes:
  fshop_postgres_data:
  fshop_redis_data:
